# Generated by Django 4.2 on 2024-10-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0002_perfume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to.',
                related_name='employee_set',
                to='auth.group',
                verbose_name='groups'
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='employee_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
